### ISSUE TITLE
Feature request: jump to <lambda> definition

### ISSUE THREAD

**Issue by lifepillar** [lacygoill/vim9asm#3]
Consider a function returning a lambda, e.g.:

```vim
﻿﻿def g:I(): func(any): any
  return (x) => (x)
enddef
```

When I `Disassemble` this, I get something like:

```
I
  return (x) => (x)
   0 FUNCREF <lambda>200
   1 RETURN
```

It would be nice if the plugin would allow you to jump to the definition of the lambda, perhaps with CTRL-].

**Comment by lacygoill** [comment]
> It would be nice if the plugin would allow you to jump to the definition of the lambda, perhaps with CTRL-].

I guess the jump would be from the Vim9 code to the relevant compiled instruction.

We would need two regexes, one matching a Vim9 lambda, and another to match the generated instruction.

I've just pushed a commit which tries to implement the feature.

One issue is that the Vim9 code could be arbitrarily complex (e.g. nested lambdas all over the place); in which case, I don't know how to find the right instruction.  For the moment, I've simply set the search register with a broad regex; this way, if we don't land on the right instruction, we just need to press `n` one or a few more times.

**Comment by lacygoill** [comment]
> I've just pushed a commit which tries to implement the feature.

It's [this one](https://github.com/lacygoill/vim9asm/commit/c93e727f481f83eefb5ce40456936aaa99028e91).

In the previous example, the cursor being anywhere where there is a `^` or `-` below:

    I
      return (x) => (x)
             ^--------^
       0 FUNCREF <lambda>200
       1 RETURN

Pressing `C-]` should make the cursor jump to the `FUNCREF` instruction.

**Comment by lifepillar** [comment]
My apologies, now I realize my request wasn't clear… What I was asking is (I think) much simpler: with the cursor over `<lambda>200`, pressing CTRL-] would jump to the disassembly of `<lambda>200`. Essentially, by calling `:Disassemble <lambda>200`—maybe reusing the same window instead of splitting.

What you have implemented seems also useful: not sure how robust you can make it.

**Comment by lacygoill** [comment]
Ah ok, I misunderstood.  So, I've pushed another commit to implement this feature instead of the previous one.  It seems to work against the example in the OP.  For the moment, `<C-]>` doesn't split the window; it just re-uses the current window.  But it also adds an entry in the jumplist; so – after pressing `<C-]>` – `<C-o>` and `<C-i>` can cycle between the instructions of the main function, and the ones of the lambda.

**Comment by lifepillar** [comment]
Thanks, this works exactly as I expected.
