### ISSUE TITLE
Sometimes, :Disassemble cannot complete functions

### ISSUE THREAD

**Issue by lifepillar** [lacygoill/vim9asm#4]
I sometimes try to complete a function's name at the command prompt without success, despite the fact that the function is compiled. I can reproduce it with this script:

```vim
vim9script

def Success(ctx: dict<any>, value: any): dict<any>
  return { success: true }
enddef

def Failure(ctx: dict<any>, value: any): dict<any>
  return { success: false }
enddef

def Str(match: string): func(dict<any>): dict<any>
  return (d) => {
    return d
  }
enddef

defcompile
```

Steps to reproduce:

1. `source %`
2. `:Disassemble *St<tab>`

After pressing Tab, I would expect `*St` to be expanded to something like `<SNR>_NN_Str(`, but that does not happen. I can complete the other two functions, though (if it works for you with all the functions, try sourcing the script once more, then try completing again). On the other hand, completing with the built-in `:disassemble` works fine.

Using Vim 8.2.3350 and the current vim9asm master.

**Comment by lacygoill** [comment]
Possibly fixed by [8.2.3360](https://github.com/vim/vim/releases/tag/v8.2.3360).
